sudo: false

env:
  global:
    - DENO_VERSION=v0.40.0

cache:
  directories:
    - $HOME/.cache/deno

before_install:
  - curl -L https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - deno test test/
